name: flutter_firebase
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^1.1.1
  firebase_database: ^3.1.6
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  firebase_storage: ^3.1.6
  intl: ^0.16.1
  image_picker: ^0.6.7+4
  simple_animations: ^1.3.3
  local_auth: ^0.6.2+3


  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/google_logo.png
    - assets/images/background.png
    - assets/images/background-2.png

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf

